languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = "true"
enableEmoji = "true"

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

baseURL = "https://example.com/"
title = "Example - CV"

[params]
colorLight = "#fff"
colorDark = "#666"
colorPageBackground = "#ddd"
colorPrimary = "#236CA4"
colorSecondary = "#aaa"
colorIconPrimary = "#fff"
colorIconBackground = "#236CA4"
colorRightColumnBackground = "#f5f5f5"
colorRightColumnHeadingText = "#666"
colorRightColumnBodyText = "#666"
colorRightColumnIconPrimary = "#fff"
colorRightColumnIconBackground = "#236CA4"
pages = 1
